[package]
name = "spring-sqlx-migration-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
spring = { version = "0.2.2" }
serde = { version = "1", features = ["derive"] }
spring-sqlx = { version = "0.2.1", features = ["postgres"] }
sqlx = { version = "0.7" }
